export const vehicleBrands = [
  { value: "toyota", label: "Toyota" },
  { value: "honda", label: "Honda" },
  { value: "hyundai", label: "Hyundai" },
  { value: "kia", label: "Kia" },
  { value: "nissan", label: "Nissan" },
  { value: "mazda", label: "Mazda" },
  { value: "mitsubishi", label: "Mitsubishi" },
  { value: "suzuki", label: "Suzuki" },
  { value: "chevrolet", label: "Chevrolet" },
  { value: "ford", label: "Ford" },
  { value: "fiat", label: "Fiat" },
  { value: "volkswagen", label: "Volkswagen" },
  { value: "bmw", label: "BMW" },
  { value: "mercedes", label: "Mercedes-Benz" },
  { value: "audi", label: "Audi" },
  { value: "jeep", label: "Jeep" },
  { value: "dodge", label: "Dodge" },
  { value: "renault", label: "Renault" },
  { value: "peugeot", label: "Peugeot" },
  { value: "citroen", label: "Citroën" },
  { value: "volvo", label: "Volvo" },
  { value: "subaru", label: "Subaru" },
  { value: "lexus", label: "Lexus" },
  { value: "porsche", label: "Porsche" },
  { value: "land rover", label: "Land Rover" },
  { value: "jaguar", label: "Jaguar" },
  { value: "infiniti", label: "Infiniti" },
  { value: "acura", label: "Acura" },
  { value: "otro", label: "Otro" },
];

export const vehicleColors = [
  { value: "blanco", label: "Blanco" },
  { value: "negro", label: "Negro" },
  { value: "gris", label: "Gris" },
  { value: "plata", label: "Plata" },
  { value: "rojo", label: "Rojo" },
  { value: "azul", label: "Azul" },
  { value: "verde", label: "Verde" },
  { value: "amarillo", label: "Amarillo" },
  { value: "naranja", label: "Naranja" },
  { value: "marron", label: "Marrón" },
  { value: "beige", label: "Beige" },
  { value: "dorado", label: "Dorado" },
  { value: "morado", label: "Morado" },
  { value: "rosa", label: "Rosa" },
  { value: "turquesa", label: "Turquesa" },
  { value: "otro", label: "Otro" },
];

export const vehicleModels: Record<string, { value: string; label: string }[]> = {
  toyota: [
    { value: "corolla", label: "Corolla" },
    { value: "camry", label: "Camry" },
    { value: "rav4", label: "RAV4" },
    { value: "highlander", label: "Highlander" },
    { value: "tacoma", label: "Tacoma" },
    { value: "4runner", label: "4Runner" },
    { value: "sequoia", label: "Sequoia" },
    { value: "prius", label: "Prius" },
    { value: "yaris", label: "Yaris" },
    { value: "hilux", label: "Hilux" },
    { value: "land cruiser", label: "Land Cruiser" },
  ],
  honda: [
    { value: "civic", label: "Civic" },
    { value: "accord", label: "Accord" },
    { value: "crv", label: "CR-V" },
    { value: "hr-v", label: "HR-V" },
    { value: "pilot", label: "Pilot" },
    { value: " Odyssey", label: "Odyssey" },
    { value: "fit", label: "Fit" },
    { value: "city", label: "City" },
    { value: "brv", label: "BR-V" },
  ],
  hyundai: [
    { value: "elantra", label: "Elantra" },
    { value: "sonata", label: "Sonata" },
    { value: "tucson", label: "Tucson" },
    { value: "santa fe", label: "Santa Fe" },
    { value: "creta", label: "Creta" },
    { value: "venue", label: "Venue" },
    { value: "palisade", label: "Palisade" },
    { value: "ioniq", label: "IONIQ" },
  ],
  kia: [
    { value: "forte", label: "Forte" },
    { value: "k5", label: "K5" },
    { value: "sportage", label: "Sportage" },
    { value: "sorento", label: "Sorento" },
    { value: "telluride", label: "Telluride" },
    { value: "soul", label: "Soul" },
    { value: "sonet", label: "Sonet" },
    { value: "niro", label: "Niro" },
  ],
  nissan: [
    { value: "sentra", label: "Sentra" },
    { value: "altima", label: "Altima" },
    { value: "rogue", label: "Rogue" },
    { value: "murano", label: "Murano" },
    { value: "pathfinder", label: "Pathfinder" },
    { value: "frontier", label: "Frontier" },
    { value: "kicks", label: "Kicks" },
    { value: "leaf", label: "LEAF" },
  ],
  mazda: [
    { value: "mazda3", label: "Mazda3" },
    { value: "mazda6", label: "Mazda6" },
    { value: "cx-5", label: "CX-5" },
    { value: "cx-9", label: "CX-9" },
    { value: "cx-30", label: "CX-30" },
    { value: "cx-50", label: "CX-50" },
    { value: "mx-5", label: "MX-5 Miata" },
  ],
  chevrolet: [
    { value: "spark", label: "Spark" },
    { value: "onix", label: "Onix" },
    { value: "beat", label: "Beat" },
    { value: "malibu", label: "Malibu" },
    { value: "trax", label: "Trax" },
    { value: "equinox", label: "Equinox" },
    { value: "traverse", label: "Traverse" },
    { value: "tahoe", label: "Tahoe" },
    { value: "silverado", label: "Silverado" },
    { value: "camaro", label: "Camaro" },
  ],
  ford: [
    { value: "fiesta", label: "Fiesta" },
    { value: "focus", label: "Focus" },
    { value: "fusion", label: "Fusion" },
    { value: "escape", label: "Escape" },
    { value: "explorer", label: "Explorer" },
    { value: "edge", label: "Edge" },
    { value: "bronco", label: "Bronco" },
    { value: "ranger", label: "Ranger" },
    { value: "f-150", label: "F-150" },
    { value: "mustang", label: "Mustang" },
  ],
};

export function getModelsForBrand(brand: string): { value: string; label: string }[] {
  return vehicleModels[brand.toLowerCase()] || [];
}